### ISSUE TITLE
Conversion to YAML removes screenshots?

### ISSUE THREAD

**Issue by probonopd** [ximion/appstream#131]
When converting [this input file](https://github.com/AppImage/AppImageHub/blob/5c123acc7dda9e07d06f10e8c4392b7e8d1a731c/database/VLC/vlc.appdata.xml)

```
...
    <screenshots>
        <screenshot type="default">http://images.videolan.org/vlc/screenshots/2.0.0/vlc-2.0-poney.jpg</screenshot>
        <screenshot type="default">http://images.videolan.org/vlc/screenshots/2.0.0/vlc-2.0-gnome3-open.jpg</screenshot>
        <screenshot type="default">http://images.videolan.org/vlc/screenshots/2.0.0/vlc-2.0-gnome3-debian.jpg</screenshot>
    </screenshots>
</component>
```

then I get [this output file](https://github.com/AppImage/AppImageHub/blob/5c123acc7dda9e07d06f10e8c4392b7e8d1a731c/database/VLC/appdata.yaml)

```
...
Screenshots:
- default: true
  thumbnails: []
- default: true
  thumbnails: []
- default: true
thumbnails: []
```

```
me@host:~$ ./appstreamcli-x86_64.AppImage --version
AppStream CLI tool version: 0.11.4
```
