### ISSUE TITLE
Convert xml to yml doesn't preserve artifacts information

### ISSUE THREAD

**Issue by ognarb** [ximion/appstream#267]
Hi, I added artifacts information to the Krita AppStream file: https://invent.kde.org/kde/krita/-/merge_requests/295/diffs.

But when converting the XML AppStream file to YAML using `appstreamcli convert`, this information is removed.

```
Releases:
- version: 4.2.9.0
  type: stable
  unix-timestamp: 1585180800
  url:
    details: https://krita.org/en/item/krita-4-2-9-released/
- version: 4.2.8.0
  type: stable
  unix-timestamp: 1574812800
  url:
    details: https://krita.org/en/item/krita-4-2-8-released/
- version: 4.2.7.1
  type: stable
  unix-timestamp: 1552176000
  url:
    details: https://krita.org/en/item/krita-4-2-7-released/
```

The file is converted when building kde.org/applications, I didn't write the extractor but I guess the reason we convert the file is that it is easier to load a YAML file. This could be changed to load the XML file directly but I prefer not touching a working system without good reasons :-) 

```
appstreamcli --version
AppStream version: 0.12.10
```
