### ISSUE TITLE
Searching is too locale-specific

### ISSUE THREAD

**Issue by aleixpol** [ximion/appstream#419]
It seems many apps translate their name, this works alright and it must have some advantages, but it makes certain products hard to find.

See how it was described here:
https://bugs.kde.org/show_bug.cgi?id=455278

**Comment by ximion** [comment]
This is a very weird bug... We should probably explicitly add the english project name to the index, but in case of GIMP, GIMP has a `<keyword>` tag with `GIMP` so it should always be found.
Running:
```yaml
~$ appstreamcli s gimp
Bezeichner: gimp-data-extras [addon]
Name: Zusätzliche Dateien für GIMP
Zusammenfassung: Muster, Farbverläufe und weitere zusätzliche Dateien für GIMP
Paket: gimp
Homepage: https://www.gimp.org/
---
Bezeichner: org.gimp.GIMP.Manual [addon]
Name: GIMP User Manual
Zusammenfassung: GIMP User Manual
Paket: flatpak:runtime/org.gimp.GIMP.Manual/x86_64/2.10
Homepage: https://gimp.org/
---
Bezeichner: org.gimp.GIMP.Plugin.Lensfun [addon]
Name: GimpLensfun
Zusammenfassung: GimpLensfun is a Gimp plugin to correct lens distortion using the lensfun library and database.
Paket: flatpak:runtime/org.gimp.GIMP.Plugin.Lensfun/x86_64/2-3.36
Homepage: https://seebk.github.io/GIMP-Lensfun/
---
Bezeichner: org.gimp.GIMP.Plugin.BIMP [addon]
Name: BIMP
Zusammenfassung: 
  Batch Image Manipulation Program, a GIMP plugin to apply a set of manipulations to an entire
  group of images!
Paket: flatpak:runtime/org.gimp.GIMP.Plugin.BIMP/x86_64/2-3.36
Homepage: https://alessandrofrancesconi.it/projects/bimp/
---
Bezeichner: org.gimp.GIMP.Plugin.Fourier [addon]
Name: Fourier
Zusammenfassung: A simple GIMP plug-in to do fourier transform on your image.
Paket: flatpak:runtime/org.gimp.GIMP.Plugin.Fourier/x86_64/2-3.36
Homepage: https://www.lprp.fr/gimp_plugin_en/
---
Bezeichner: org.gimp.GIMP.Plugin.Resynthesizer [addon]
Name: Resynthesizer
Zusammenfassung: Set of GIMP plug-ins that heal (in-paint), synthesize texture, theme an image, and more
Paket: flatpak:runtime/org.gimp.GIMP.Plugin.Resynthesizer/x86_64/2-3.36
Homepage: http://logarithmic.net/pfh/resynthesizer
---
Bezeichner: org.gimp.GIMP [desktop-application]
Name: GNU Image Manipulation Program
Zusammenfassung: Bilder erstellen und Fotografien bearbeiten
Paket: gimp
Homepage: https://www.gimp.org/
Symbol: gimp_gimp.png
---
Bezeichner: org.gimp.GIMP [desktop-application]
Name: GNU Image Manipulation Program
Zusammenfassung: Bilder erstellen und Fotografien bearbeiten
Paket: flatpak:app/org.gimp.GIMP/x86_64/stable
Homepage: https://www.gimp.org/
Symbol: org.gimp.GIMP.png
[...]
```
![grafik](https://user-images.githubusercontent.com/417468/185804838-f7407fee-424a-4ca7-b76e-eed2dd5b185e.png)

So, I think for the bug you linked there must be something else wrong as well...
