### ISSUE TITLE
Exact match of  the search doesn't appear on the top / relevance order is broken

### ISSUE THREAD

**Issue by kha84** [ximion/appstream#424]
Raised this first for plasma-discover (https://invent.kde.org/plasma/discover/-/issues/18), but they're saying it's using the appstream and suggested to raise a ticket here. 

Here's the simple example - I tried to search for "konqueror" I can only find it at ~ hundred position from the top, when the results are sorted by relevance (I think this is what plasma-discover guys are using now by default)

![Screenshot_20220820_161811](https://user-images.githubusercontent.com/110789576/185756658-500280d5-987e-40c6-9671-90b3c18c8738.png)

**Comment by ximion** [comment]
That's because you misspelled "konqueror" - correcting spelling mistakes is super difficult and we don't really do that.
If you search for the right thing exactly, it will show up at the top:
![grafik](https://user-images.githubusercontent.com/417468/185758113-7a246cc3-0b2d-4b67-be67-9e99195f4c3c.png)

**Comment by kha84** [comment]
Sure, thx that do make a lot of sense. Looks like I was just foolishly hoping the relevance sorting is smart enough to figure it out itself.

**Comment by kha84** [comment]
One last question on the same topic - if I put just "konq" as a search token, I still can see a lot of irrelevant apps in the top search results, which are having "konq" neither in their names nor in the description. That doesn't sound right to me:

![Screenshot_20220820_171341](https://user-images.githubusercontent.com/110789576/185758966-4378aa7d-588d-49f6-af35-c79c953f0cde.png)

**Comment by ximion** [comment]
Hmm, something seems to either be broken in Discover or odd with your setup. Because:
```yaml
~$ appstreamcli search konq
Identifier: org.kde.konquest.desktop [desktop-application]
Name: Konquest
Summary: Galaktisches Strategiespiel
Package: konquest
Homepage: https://apps.kde.org/konquest
Icon: konquest_konquest.png
---
Identifier: org.kde.konquest.desktop [desktop-application]
Name: Konquest
Summary: Galaktisches Strategiespiel
Bundle: flatpak:app/org.kde.konquest/x86_64/stable
Homepage: https://apps.kde.org/konquest
Icon: org.kde.konquest.png
---
Identifier: org.kde.konqueror.desktop [desktop-application]
Name: Konqueror
Summary: Dateiverwaltung & Webbrowser von KDE
Package: konqueror
Homepage: https://www.konqueror.org
Icon: konqueror_konqueror.png
---
Identifier: org.kde.filelight.desktop [desktop-application]
Name: Filelight
Summary: 
  Filelight zeigt Diagramme aus konzentrischen Ringen an, die die Belegung von Speichermedien auf
  ihrem Rechner darstellen
Package: filelight
Homepage: https://kde.org/applications/en/utilities/org.kde.filelight
Icon: filelight_filelight.png
[...]
```
Likewise:
![grafik](https://user-images.githubusercontent.com/417468/185760266-5107ea0c-fc44-460c-9990-94678eab44b1.png)

It is really weird that you get "KAtomic" though, you can maybe try searching with `appstreamcli` and see if you get the same result!
