### ISSUE TITLE
Missing categories seems harsh

### ISSUE THREAD

**Issue by bbhtt** [ximion/appstream#577]
https://github.com/ximion/appstream/commit/708a84f523fa99646c18eba5abf3f0e0aeced287#diff-a3371891dafb978899dcc13eea2c3a592e8d04be9e2d1c8b1655ba4585edfaa9R614 added mising categories as an error but this seems a bit harsh for desktop applications considering neither the appstream spec not desktop menu spec makes categories mandatory

https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-categories

Also, it seems to mandatorily require category in appdata otherwise compose fails. Considering appstream-glib and libappstream both merge categories from desktop file in presence of a launchable, a lot of applications define it in one place only.

**Comment by bbhtt** [comment]
Reproducer:

<details>
<summary> manifest </summary>

```yaml

id: org.flatpak.Hello
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk
command: hello

modules:

  - name: hello
    buildsystem: simple
    build-commands:
      - install -Dm755 hello.sh /app/bin/hello
    sources:
      - type: script
        dest-filename: hello.sh
        commands:
          - echo "Hello world"

  - name: metainfo
    buildsystem: simple
    build-commands:
      - install -Dm644 test.appdata.xml /app/share/appdata/$FLATPAK_ID.appdata.xml
      - install -Dm644 test.desktop /app/share/applications/$FLATPAK_ID.desktop
      - install -Dm644 test.svg /app/share/icons/hicolor/scalable/apps/$FLATPAK_ID.svg
    sources:
      - type: file
        path: test.appdata.xml
      - type: file
        path: test.desktop
      - type: file
        path: test.svg
```
</details>

<details>
<summary> desktop file </summary>

```
[Desktop Entry]
Name=Foo
Exec=hello
Icon=org.flatpak.Hello
Terminal=false
Type=Application
StartupNotify=true
Categories=GTK;
```

</details>

<details>

<summary> appdata </summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
  <id>org.flatpak.Hello</id>
  <metadata_license>CC0-1.0</metadata_license>
  <project_license>GPL-3.0-or-later</project_license>
  <content_rating type="https://odrs.gnome.org/oars"/>
  <launchable type="desktop-id">org.flatpak.Hello.desktop</launchable>
  <name>Hello</name>
  <summary>A hello world flatpak</summary>
  <description>
    <p>A hello world flatpak to test. This is a test. This is a test. This is a test.  This is a test.  This is a test.  This is a test.  This is a test.  This is a test.</p>
  </description>
  <screenshots>
    <screenshot type="default">
      <image>https://upload.wikimedia.org/wikipedia/commons/a/af/Tux.png</image>
      <caption>A tux logo</caption>
    </screenshot>
  </screenshots>
  <url type="homepage">https://github.com/FailurePoint/RandomNumberFive</url>
  <releases>
    <release version="1.2.1" date="2023-12-31" />
  </releases>
  <developer_name>Foo</developer_name>
</component>

```

```
flatpak-builder --version                                  
flatpak-builder-1.4.0

appstreamcli --version      
AppStream version: 0.16.1
```
